package com.chetan.taskflow.user;

// <editor-fold defaultstate="collapsed" desc="Persistent account and credentials">
/*
 * Maps to users with a database-generated identity ID and a unique email column. UserService stores
 * normalized email and a BCrypt password hash; the entity itself does not normalize or hash inputs.
 * The role is stored as text and defaults to USER. Lombok supplies accessors and a JPA constructor.
 * The PrePersist callback assigns createdAt immediately before insertion, and the column cannot be
 * updated through the mapping. UserResponse deliberately excludes passwordHash from API output.
 * Database uniqueness is the final constraint; the service duplicate check alone is not atomic.
 */
// </editor-fold>

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;

@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //  PostGreSQL - id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    private Long id;

    @Column(nullable = false, length = 100) // PostGreSQL - name VARCHAR(100) NOT NULL
    private String name;

    @Column(nullable = false, unique = true, length = 255)  //  PostGreSQL - email VARCHAR(255) NOT NULL UNIQUE
    private String email;

    @Column(name = "password_hash", nullable = false, length = 255) // PostGreSQL - password_hash VARCHAR(255) NOT NULL
    private String passwordHash;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Role role = Role.USER;  //  PostGreSQL - role VARCHAR(20) NOT NULL

    @Column(name = "created_at", nullable = false, updatable = false)   //  PostGreSQL - created_at TIMESTAMPTZ NOT NULL
    private Instant createdAt;

    // <editor-fold defaultstate="collapsed" desc="Assign creation time at persistence">
    /*
     * JPA invokes this callback before an initial insert. It uses the application clock, not a
     * database default. updatable=false on the column preserves the initial value on later updates.
     */
    // </editor-fold>
    @PrePersist
    private void setCreatedAt() {
        createdAt = Instant.now();
    }

//    CREATE TABLE users (
//    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    name VARCHAR(100) NOT NULL,
//    email VARCHAR(255) NOT NULL UNIQUE,
//    password_hash VARCHAR(255) NOT NULL,
//    role VARCHAR(20) NOT NULL,
//    created_at TIMESTAMPTZ NOT NULL
//  );
}
