package com.chetan.taskflow.user;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;

@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //  PostGreSQL - id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    private Long id;

    @Column(nullable = false, length = 100) // PostGreSQL - name VARCHAR(100) NOT NULL
    private String name;

    @Column(nullable = false, unique = true, length = 255)  //  PostGreSQL - email VARCHAR(255) NOT NULL UNIQUE
    private String email;

    @Column(name = "password_hash", nullable = false, length = 255) // PostGreSQL - password_hash VARCHAR(255) NOT NULL
    private String passwordHash;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Role role = Role.USER;  //  PostGreSQL - role VARCHAR(20) NOT NULL

    @Column(name = "created_at", nullable = false, updatable = false)   //  PostGreSQL - created_at TIMESTAMPTZ NOT NULL
    private Instant createdAt;

    @PrePersist
    private void setCreatedAt() {
        createdAt = Instant.now();
    }

//    CREATE TABLE users (
//    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    name VARCHAR(100) NOT NULL,
//    email VARCHAR(255) NOT NULL UNIQUE,
//    password_hash VARCHAR(255) NOT NULL,
//    role VARCHAR(20) NOT NULL,
//    created_at TIMESTAMPTZ NOT NULL
//  );
}
